name: dliocode-translate-md

on:
  push:
    branches:
      - v3
    paths:
      - 'README.md'    	  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages                  
      - name: Adding README - English
        uses: dliocode/translate-md@main
        with:
          LANG_TO: en
